routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::delete('/cart/clear', 'CartController@clear')->name('cart.clear');
Route::resource('order','OrderController');
Route::resource('products','ProductController');
Route::resource('categories','CategoryController');
Route::resource('branch','BranchController');
Route::resource('transaction','TransactionController');
Route::resource('cart','CartController');


Route::get('/home', 'HomeController@index')->name('home');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public function category()
	{
		return $this->belongsTo('App\Category');
	}

	public function order()
	{
		return $this->belongsToMany('App\Order');
	}
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Category;
use App\Branch;
use Illuminate\Http\Request;
use Str;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('products.index')->with('products', $products);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $this->authorize('create', $product);
        $categories = Category::all();
        $branches = Branch::all();
        return view('products.create')->with('categories', $categories)->with('branch', $branches);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Product $products)
    {

        // $this->authorize('create', $products);
        // Flow
            // 1. Validate each field (validation errors will display in views)
            // 2. save uploaded image (to get the path which will be save to the database)
            // 3. get input values from form
            // 4. save the details to the database
            // 5. redirect user to view the newly created product

        //==============================================
        // 1. Validate each field (validation errors will display in views)
        $request->validate([
            'name' => 'required|string',
            'category_id' => 'required',
            'image' => 'required|image',
            'stock' => 'required|numeric',
            'description' => 'required|string'
        ]);


        //==============================================
        // 2. save uploaded image (to get the path which will be save to the database)
            // 2.1 get uploaded file
            // 2.2 get uploaded filename
            // 2.3 get uploaded file extension name
            // 2.4 generate new name with random characters
            // 2.5 save the new file to public folder

            //====================================
            // 2.1 get uploaded file

        $category_code = Category::find($request->input('category_id'));

        $file = $request->file('image');
            // dd($file);

            // 2.2 get uploaded filename
        $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);

            // 2.3 get uploaded file extension name
        $file_extension = $file->extension();

            // 2.4 generate new name with random characters
        $random_chars = Str::random(10);


        $final_code = $category_code->name . "_" . date('Y-m-d-H-i-s') . $random_chars;
        $new_file_name = date('Y-m-d-H-i-s') . "_" . $random_chars . "_" . $file_name . "." .  $file_extension;


        // if($category_code-> == 0){
        //     return $stockfile = true;
        // }else{
        //     return $stockfile = false;
        // }

            // 2.5 save the new file to public folder
        $filepath =  $file->storeAs('images',$new_file_name, 'public' );


        //==============================================
             // 3. get input values from form
        $name = $request->input('name');
        $category_id = $request->input('category_id');
        $image = $filepath;
        $stock = $request->input('stock');
        $code = $final_code;
        $description = $request->input('description');

        //==============================================
            // 4. save the details to the database
        $product = new Product;
        $product->name =$name;
        $product->category_id =$category_id;
        $product->image = $filepath;
        $product->stock =$stock;
        $product->code = $final_code;
        $product->description =$description;
        $product->save();

            // 5. redirect user to view the newly created product
        return redirect( route('products.show', ['product' => $product->id] ));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(product $product)
    {
        return view('products.show')
        ->with("product", $product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(product $product)
    {
        $categories = Category::all();
        return view('products.edit')
        ->with('product',$product)
        ->with("categories", $categories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, product $product)
    {
        // $this->authorize('create', $products);
        // Flow
            // 1. Validate the form, check if all field are not empty
            // 2. Update database if there are differences between the detials form form and the current detials of the product
        // ==============================
            // 1. Validate the form, check if all field are not empty
        $request->validate([
            'name' => 'required|string',
            'category_id' => 'required',
            'image' => 'required|image',
            'stock' => 'required|numeric',
            'description' => 'required|string'
        ]);


    // 2. Update database if there are differences between the detials form form and the current details 
        if(
            !$request->hasFile('image') && 
            $product->name == $request->input('name') &&
            $product->description == $request->input('description') &&
            $product->stock == $request->input('stock') &&
            $product->category_id == $request->input('category_id')
            
        ){
            $request->session()->flash('update_failed','Something went wrong!');
            
        }else{
            // update the entry in the database and return the updated entry

            // check if there is a file uploaded
            if($request->hasFile('image')){
                $request->validate([
                    'image' => 'required|image',
                ]);

                // 2.1 get uploaded file
                $file = $request->file('image');
                // dd($file);

                // 2.2 get uploaded filename
                $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);

                // 2.3 get uploaded file extension name
                $file_extension = $file->extension();

                // 2.4 generate new name with random characters
                $random_chars = Str::random(10);
                $new_file_name = date('Y-m-d-H-i-s') . "_" . $random_chars . "_" . $file_name . "." .  $file_extension;

                // 2.5 save the new file to public folder
                $filepath =  $file->storeAs('images',$new_file_name, 'public' );

                // set the new image path as image value of product
                $product->image=$filepath;

            }

            // update the product attribute
            $product->name = $request->input('name');
            $product->stock = $request->input('stock');
            $product->description = $request->input('description');
            $product->category_id = $request->input('category');

            $product->save();

            $request->session()->flash('update_sucess','Product Successfully Update');

        }

        return redirect( route('products.edit',['product' => $product->id]));
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(product $product)
    {
        $product->delete();
        // $request->session()->flash('destroy_sucess','Product Deleted');
        return redirect(route('products.index'))->with('destroy_message','Product Deleted');
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')



<div class="container">
	<div class="row">
		<div class="col-8 col-md-8 mx-auto">
			<h3 class="text-center">Create a new Product</h3>
			<hr>

			<form action="{{ route('products.store') }}" method="post" enctype="multipart/form-data">
				@csrf

				{{-- name --}}
				<div class="form-group">
					<label for="name">Product Name: </label>
					<input type="text" name="name" class="form-control" id="name">
				</div>
				@if($errors->has('name'))
				<div class="alert alert-danger">
					<small class="mb-0">Product name Required</small>
				</div>
				@endif

				{{-- category --}}
				<div class="form-group">
					<label for="category_id">Category</label>
					<select class="form-control" id="category_id" name="category_id">
						@foreach($categories as $category)
						<option value="{{ $category->id}}">{{$category->name}}</option>
						@endforeach
					</select>
				</div>
				@if($errors->has('category'))
				<div class="alert alert-danger">
					<small class="mb-0">Product category required</small>
				</div>
				@endif

				{{-- branch --}}
				<div class="form-group">
					<label for="category_id">Branch</label>
					<select class="form-control" id="category_id" name="category_id">
						@foreach($branch as $branch)
						<option value="{{ $branch->id}}">{{$branch->name}}</option>
						@endforeach
					</select>
				</div>
				@if($errors->has('category'))
				<div class="alert alert-danger">
					<small class="mb-0">Product category required</small>
				</div>
				@endif

				{{-- image --}}
				<div class="form-group">
					<label for="image">Image:  </label>
					<input type="file" name="image" class="form-control-file" id="image">
				</div>
				@if($errors->has('image'))
				<div class="alert alert-danger">
					<small class="mb-0">Product image required, Check your image file</small>
				</div>
				@endif

				{{-- quantity and mass --}}
				<div class="form-group">
					<label for="stock">Stocks: </label>
					<input class="form-control" min="0" name="stock" value="1" type="number">
				</div>
				@if($errors->has('stock'))
				<div class="alert alert-danger">
					< class="mb-0">Product Stocks required</small>
				</div>
				@endif

				{{-- description --}}
				<div class="form-group">
					<label>Description: </label>
					<textarea name="description" class="form-control" cols="30" rows="5" id="description"></textarea>
				</div>
				@if($errors->has('description'))
				<div class="alert alert-danger">
					<small class="mb-0">Product description required,</small>
				</div>
				@endif


				<button class="btn btn-outline-primary w-100">Add Item</button>

				
			</div>

		</form>
		<div class="col-12 col-md-3 mt-5">
			@if (Session::has('category_message'))
			<div class="alert alert-success">
				<small>{{Session::get('category_message')}}</small>
			</div>
			@endif
			@if ($errors->has('add-category'))
			<div class="alert alert-danger">
				<small>Category Not Added</small>
			</div>
			@endif
			<form method="POST" action="{{route('categories.store')}}">
				@csrf

				<div class="form-group">
					<label for="add-category">Add Category</label>
					<input type="text" name="add-category" id="add-category" class="form-control">
				</div>
				<button class="btn btn-secondary btn-block">Add category</button>

			</form>

		</form>
		<div class="col-12 col-md-3 mt-5">
			@if (Session::has('category_message'))
			<div class="alert alert-success">
				<small>{{Session::get('category_message')}}</small>
			</div>
			@endif
		</div>
	
		{{-- end of category --}}

		<div class="col-12 col-md-12 mt-5">
			@if (Session::has('branch_message'))
			<div class="alert alert-success">
				<small>{{Session::get('branch_message')}}</small>
			</div>
			@endif
			@if ($errors->has('add-branch'))
			<div class="alert alert-danger">
				<small>Branch Not Added</small>
			</div>
			@endif
			<form method="POST" action="{{route('branch.store')}}">
				@csrf

				<div class="form-group">
					<label for="add-branch">Add Branch</label>
					<input type="text" name="add-branch" id="add-branch" class="form-control">
				</div>

				<div class="form-group">
					<label for="address">Address </label>
					<input type="text" name="address" id="address" class="form-control">
				</div>
				<button class="btn btn-secondary btn-block">Add branch</button>

			</form>

		</form>
		</div>
	</div>

		
</div>
		
	</div>

</div>

@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
	<div class="row">
		<div class="col-12 col-md-8 mx-auto">
			<h3 class="text-center">Create a new Product</h3>
			<hr>

			@if(Session::has('update_failed'))
			<div class="alert alert-warning">{{ Session::get('update_failed') }}</div>
			@endif

			@if(Session::has('update_sucess'))
			<div class="alert alert-success">
				{{Session::get('update_sucess')}}
			</div>
			@endif

			<form action="{{ route('products.update', ['product' =>$product->id]) }}" method="POST" enctype="multipart/form-data">
				@csrf
				@method('PUT')

				{{-- name --}}
				<div class="form-group">
					<label for="name">Product Name: </label>
					<input type="text" name="name" class="form-control" id="name" value="{{$product->name}}">
				</div>
				@if($errors->has('name'))
				<div class="alert alert-danger">
					<small class="mb-0">Product name Required</small>
				</div>
				@endif

				{{-- category --}}
				<div class="form-group">
					<label for="category_id">Category</label>
					<select class="form-control" id="category_id" name="category_id">
						@foreach($categories as $category)
						<option value="{{ $category->id}}">{{$category->name}}</option>
						@endforeach
					</select>
				</div>

				@if($errors->has('category'))
				<div class="alert alert-danger">
					<small class="mb-0">Product category required</small>
				</div>
				@endif

				{{-- image --}}
				<div class="form-group">
					<label for="image">Image:  </label>
					<input type="file" name="image" class="form-control-file" id="image" value="{{$product->image}}">
				</div>
				@if($errors->has('image'))
				<div class="alert alert-danger">
					<small class="mb-0">Product image required, Check your image file</small>
				</div>
				@endif

				{{-- quantity and mass --}}
				<div class="form-group">
					<label>Stock: </label>
					<input class="form-control" min="0" name="stock" value="{{$product->stock}}" type="number">
				</div>
				@if($errors->has('quantity'))
				<div class="alert alert-danger">
					<small class="mb-0">Product stock required</small>
				</div>

				@elseif($errors->has('weight'))
				<div class="alert alert-danger">
					<small class="mb-0">Product price required</small>
				</div>
				@endif

				{{-- description --}}
				<div class="form-group">
					<label>Description: </label>
					<textarea name="description" class="form-control" cols="30" rows="5" id="description" >{{$product->description}}</textarea>
				</div>
				@if($errors->has('description'))
				<div class="alert alert-danger">
					<small class="mb-0">Product description required,</small>
				</div>
				@endif


				<button class="btn btn-outline-primary w-100">update</button>


			</form>
		</div>
	</div>
</div>

@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')

@if(Session::has('destroy_message'))
<div class="alert alert-success">
	{{ Session::get('destroy_message') }}	
</div>
@endif
<div class="container">
	<div class="row">
		<div class="col-12 col-md-8 mx-auto">
			<div class="jumbotron">
				<h1 class="text-center">Online Storage</h1>
			</div>
		</div>
	</div>



	<div class="row">
		<div class="col-12 col-md-10 mx-auto">
			<div class="row">

				{{-- @if($products->category_id === 1) --}}
				@foreach($products as $product)
				<div class="col-12 col-md-4">
					{{-- {{dd($product)}} --}}
					{{-- <h2 class="text-center">{{$product->category->name}}</h2> --}}
					<div class="card ">
						<img src="{{ url('/public/' .$product->image) }}" class="card-img-top cardImg">
						<div class="card-body cardImg">
							
							<h2 class="card-title">{{ $product->name }}</h2>
							<p class="card-text">
								<strong>
								Stock: {{number_format( $product->stock) }}
								</strong>
							</p>

							<p class="card-text">
								{{ $product->description}}
							</p>

						</div>
					</div>
					
					<div class="card-footer">
						{{-- Add to cart button --}}

						<form action="{{ route('cart.store') }}" method="POST" class="add-to-cart-field">
							@csrf

							<div class="form-group">

								<input type="hidden" name="id" value="{{$product->id}}">
								<label for="quantity">Quantity</label>
								<div class="input-group mb-3">
									
									<div class="input-group-prepend">
										<button class="btn btn-outline-secondary deduct-quantity" data-id= "{{$product->id}}" type="button" >-</button>
									</div>
									
									<input 
									type="text"
									value="1" 
									name="stock" 
									class="form-control input-quantity" 
									placeholder="Enter Quantity" 
									data-id= "{{$product->id}}"
									>
									
									<div class="input-group-append">
										<button class="btn btn-outline-secondary add-quantity" data-id= "{{$product->id}}" type="button">+</button>
									</div>
								</div>
							</div>
							<button class="btn btn-outline-success my-1 w-100 ">Add to cart</button>
						</form>
												<a
						class="btn btn-block btn-outline-dark my-1" 
						href="{{ route('products.show', ['product' => $product->id]) }}">
						View Product
					</a>
					
					<a 
					href="{{ route('products.edit', ['product' => $product->id]) }}" 
					class="btn btn-outline-info w-100 my-1">Edit Product
				</a>

				<form action="{{ route('products.destroy', ['product' => $product->id])}}" method="post">
					@csrf
					@method('DELETE')

					<button {{ route('products.destroy', ['product' => $product->id]) }}" class="btn btn-outline-danger w-100  my-1"> Delete Product
					</button>

				</form>
			</div>

		</div>
		@endforeach
		{{-- @endif --}}
	</div>
</div>
</div>
</div>

@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')



<div class="container">
	<div class="row">
		<div class="col-12 col-md-8 mx-auto">
			<h3 class="text-center">View This Awesome Product</h3>
			<hr>

			<div class="card">
				<img src="{{ url('/public/' .$product->image) }}" class="card-img-top">
				<div class="card-body">
					
					<h2 class="card-title">{{ $product->name }}</h2>
					<p class="card-text">
						<strong>
							Stock:  {{ $product->stock}}
						</strong>
					</p>
					<p class="card-text">
						{{ $product->description}}
					</p>

				</div>
			</div>

			<div class="card-footer">
				{{-- Add to cart button --}}
				<a href="" class="btn btn-outline-success text-center">Add Product</a>

				<a 
				class="btn btn-block btn-outline-dark my-1" 
				href="{{ route('products.show', ['product' => $product->id]) }}">
				View Product
			</a>
		
			<a 
			href="{{ route('products.edit', ['product' => $product->id]) }}" 
			class="btn btn-outline-info w-100 my-1">Edit Product
		</a>

		<form action="{{ route('products.destroy', ['product' => $product->id])}}" method="post">
			@csrf
			@method('DELETE')
			<button {{ route('products.edit', ['product' => $product->id]) }}" class="btn btn-outline-danger w-100  my-1">Delete Product</button>

		</form>
	</div>
</div>
</div>
</div>

@endsection